# Generated by Django 6.0.7 on 2026-07-26 17:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Todo",
                "verbose_name_plural": "Todos",
                "db_table": "todo",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TodoStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, default="Pending", max_length=100, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "todo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todo_statuses",
                        to="task.todo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Todo Status",
                "verbose_name_plural": "Todo Statuses",
                "db_table": "todo_status",
                "ordering": ["-created_at"],
            },
        ),
    ]
